/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlugVideosRouteImport } from './routes/$slug/videos'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedMultistreamRouteImport } from './routes/_authenticated/multistream'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AlertsOverlayRouteImport } from './routes/alerts.overlay'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DocsPrivacyRouteImport } from './routes/docs/privacy'
import { Route as DocsTosRouteImport } from './routes/docs/tos'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedDonationsIndexRouteImport } from './routes/_authenticated/donations.index'
import { Route as ApiAlertsStreamRouteImport } from './routes/api/alerts/stream'
import { Route as ApiAlertsUploadRouteImport } from './routes/api/alerts/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChatSplatRouteImport } from './routes/api/chat/$'
import { Route as ApiRestreamMediaRouteImport } from './routes/api/restream/media'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ChatOverlayTokenRouteImport } from './routes/chat.overlay.$token'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedAdminAdminDlqRouteImport } from './routes/_authenticated/_admin/admin/dlq'
import { Route as ApiAlertsMediaAssetIdRouteImport } from './routes/api/alerts/media.$assetId'
import { Route as ApiIntegrationDonationalertsAuthorizeRouteImport } from './routes/api/integration/donationalerts/authorize'
import { Route as ApiIntegrationDonationalertsCallbackRouteImport } from './routes/api/integration/donationalerts/callback'
import { Route as ApiIntegrationStreamelementsAuthorizeRouteImport } from './routes/api/integration/streamelements/authorize'
import { Route as ApiIntegrationStreamelementsCallbackRouteImport } from './routes/api/integration/streamelements/callback'
import { Route as ApiIntegrationStreamlabsAuthorizeRouteImport } from './routes/api/integration/streamlabs/authorize'
import { Route as ApiIntegrationStreamlabsCallbackRouteImport } from './routes/api/integration/streamlabs/callback'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugVideosRoute = SlugVideosRouteImport.update({
  id: '/$slug/videos',
  path: '/$slug/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMultistreamRoute =
  AuthenticatedMultistreamRouteImport.update({
    id: '/multistream',
    path: '/multistream',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AlertsOverlayRoute = AlertsOverlayRouteImport.update({
  id: '/alerts/overlay',
  path: '/alerts/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPrivacyRoute = DocsPrivacyRouteImport.update({
  id: '/docs/privacy',
  path: '/docs/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTosRoute = DocsTosRouteImport.update({
  id: '/docs/tos',
  path: '/docs/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDonationsIndexRoute =
  AuthenticatedDonationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDonationsRoute,
  } as any)
const ApiAlertsStreamRoute = ApiAlertsStreamRouteImport.update({
  id: '/api/alerts/stream',
  path: '/api/alerts/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsUploadRoute = ApiAlertsUploadRouteImport.update({
  id: '/api/alerts/upload',
  path: '/api/alerts/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSplatRoute = ApiChatSplatRouteImport.update({
  id: '/api/chat/$',
  path: '/api/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestreamMediaRoute = ApiRestreamMediaRouteImport.update({
  id: '/api/restream/media',
  path: '/api/restream/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOverlayTokenRoute = ChatOverlayTokenRouteImport.update({
  id: '/chat/overlay/$token',
  path: '/chat/overlay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminDlqRoute =
  AuthenticatedAdminAdminDlqRouteImport.update({
    id: '/dlq',
    path: '/dlq',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const ApiAlertsMediaAssetIdRoute = ApiAlertsMediaAssetIdRouteImport.update({
  id: '/api/alerts/media/$assetId',
  path: '/api/alerts/media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationDonationalertsAuthorizeRoute =
  ApiIntegrationDonationalertsAuthorizeRouteImport.update({
    id: '/api/integration/donationalerts/authorize',
    path: '/api/integration/donationalerts/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationDonationalertsCallbackRoute =
  ApiIntegrationDonationalertsCallbackRouteImport.update({
    id: '/api/integration/donationalerts/callback',
    path: '/api/integration/donationalerts/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationStreamelementsAuthorizeRoute =
  ApiIntegrationStreamelementsAuthorizeRouteImport.update({
    id: '/api/integration/streamelements/authorize',
    path: '/api/integration/streamelements/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationStreamelementsCallbackRoute =
  ApiIntegrationStreamelementsCallbackRouteImport.update({
    id: '/api/integration/streamelements/callback',
    path: '/api/integration/streamelements/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationStreamlabsAuthorizeRoute =
  ApiIntegrationStreamlabsAuthorizeRouteImport.update({
    id: '/api/integration/streamlabs/authorize',
    path: '/api/integration/streamlabs/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationStreamlabsCallbackRoute =
  ApiIntegrationStreamlabsCallbackRouteImport.update({
    id: '/api/integration/streamlabs/callback',
    path: '/api/integration/streamlabs/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/videos': typeof SlugVideosRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/multistream': typeof AuthenticatedMultistreamRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/alerts/overlay': typeof AlertsOverlayRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/api/alerts/stream': typeof ApiAlertsStreamRoute
  '/api/alerts/upload': typeof ApiAlertsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/restream/media': typeof ApiRestreamMediaRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/donations/': typeof AuthenticatedDonationsIndexRoute
  '/admin/dlq': typeof AuthenticatedAdminAdminDlqRoute
  '/api/alerts/media/$assetId': typeof ApiAlertsMediaAssetIdRoute
  '/api/integration/donationalerts/authorize': typeof ApiIntegrationDonationalertsAuthorizeRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
  '/api/integration/streamelements/authorize': typeof ApiIntegrationStreamelementsAuthorizeRoute
  '/api/integration/streamelements/callback': typeof ApiIntegrationStreamelementsCallbackRoute
  '/api/integration/streamlabs/authorize': typeof ApiIntegrationStreamlabsAuthorizeRoute
  '/api/integration/streamlabs/callback': typeof ApiIntegrationStreamlabsCallbackRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/videos': typeof SlugVideosRoute
  '/': typeof AuthenticatedIndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/multistream': typeof AuthenticatedMultistreamRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/alerts/overlay': typeof AlertsOverlayRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/api/alerts/stream': typeof ApiAlertsStreamRoute
  '/api/alerts/upload': typeof ApiAlertsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/restream/media': typeof ApiRestreamMediaRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/donations': typeof AuthenticatedDonationsIndexRoute
  '/admin/dlq': typeof AuthenticatedAdminAdminDlqRoute
  '/api/alerts/media/$assetId': typeof ApiAlertsMediaAssetIdRoute
  '/api/integration/donationalerts/authorize': typeof ApiIntegrationDonationalertsAuthorizeRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
  '/api/integration/streamelements/authorize': typeof ApiIntegrationStreamelementsAuthorizeRoute
  '/api/integration/streamelements/callback': typeof ApiIntegrationStreamelementsCallbackRoute
  '/api/integration/streamlabs/authorize': typeof ApiIntegrationStreamlabsAuthorizeRoute
  '/api/integration/streamlabs/callback': typeof ApiIntegrationStreamlabsCallbackRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug/videos': typeof SlugVideosRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/multistream': typeof AuthenticatedMultistreamRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/alerts/overlay': typeof AlertsOverlayRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/api/alerts/stream': typeof ApiAlertsStreamRoute
  '/api/alerts/upload': typeof ApiAlertsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/restream/media': typeof ApiRestreamMediaRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/_authenticated/donations/': typeof AuthenticatedDonationsIndexRoute
  '/_authenticated/_admin/admin/dlq': typeof AuthenticatedAdminAdminDlqRoute
  '/api/alerts/media/$assetId': typeof ApiAlertsMediaAssetIdRoute
  '/api/integration/donationalerts/authorize': typeof ApiIntegrationDonationalertsAuthorizeRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
  '/api/integration/streamelements/authorize': typeof ApiIntegrationStreamelementsAuthorizeRoute
  '/api/integration/streamelements/callback': typeof ApiIntegrationStreamelementsCallbackRoute
  '/api/integration/streamlabs/authorize': typeof ApiIntegrationStreamlabsAuthorizeRoute
  '/api/integration/streamlabs/callback': typeof ApiIntegrationStreamlabsCallbackRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/videos'
    | '/alerts'
    | '/chat'
    | '/donations'
    | '/integrations'
    | '/multistream'
    | '/settings'
    | '/videos'
    | '/alerts/overlay'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/admin'
    | '/api/alerts/stream'
    | '/api/alerts/upload'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/restream/media'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/donations/'
    | '/admin/dlq'
    | '/api/alerts/media/$assetId'
    | '/api/integration/donationalerts/authorize'
    | '/api/integration/donationalerts/callback'
    | '/api/integration/streamelements/authorize'
    | '/api/integration/streamelements/callback'
    | '/api/integration/streamlabs/authorize'
    | '/api/integration/streamlabs/callback'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/videos'
    | '/'
    | '/alerts'
    | '/chat'
    | '/integrations'
    | '/multistream'
    | '/settings'
    | '/videos'
    | '/alerts/overlay'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/api/alerts/stream'
    | '/api/alerts/upload'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/restream/media'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/donations'
    | '/admin/dlq'
    | '/api/alerts/media/$assetId'
    | '/api/integration/donationalerts/authorize'
    | '/api/integration/donationalerts/callback'
    | '/api/integration/streamelements/authorize'
    | '/api/integration/streamelements/callback'
    | '/api/integration/streamlabs/authorize'
    | '/api/integration/streamlabs/callback'
    | '/admin'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$slug/videos'
    | '/_authenticated/_admin'
    | '/_authenticated/alerts'
    | '/_authenticated/chat'
    | '/_authenticated/donations'
    | '/_authenticated/integrations'
    | '/_authenticated/multistream'
    | '/_authenticated/settings'
    | '/_authenticated/videos'
    | '/alerts/overlay'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/_authenticated/'
    | '/_authenticated/_admin/admin'
    | '/api/alerts/stream'
    | '/api/alerts/upload'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/restream/media'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/_authenticated/donations/'
    | '/_authenticated/_admin/admin/dlq'
    | '/api/alerts/media/$assetId'
    | '/api/integration/donationalerts/authorize'
    | '/api/integration/donationalerts/callback'
    | '/api/integration/streamelements/authorize'
    | '/api/integration/streamelements/callback'
    | '/api/integration/streamlabs/authorize'
    | '/api/integration/streamlabs/callback'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlugVideosRoute: typeof SlugVideosRoute
  AlertsOverlayRoute: typeof AlertsOverlayRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DocsPrivacyRoute: typeof DocsPrivacyRoute
  DocsTosRoute: typeof DocsTosRoute
  ApiAlertsStreamRoute: typeof ApiAlertsStreamRoute
  ApiAlertsUploadRoute: typeof ApiAlertsUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSplatRoute: typeof ApiChatSplatRoute
  ApiRestreamMediaRoute: typeof ApiRestreamMediaRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ChatOverlayTokenRoute: typeof ChatOverlayTokenRoute
  ApiAlertsMediaAssetIdRoute: typeof ApiAlertsMediaAssetIdRoute
  ApiIntegrationDonationalertsAuthorizeRoute: typeof ApiIntegrationDonationalertsAuthorizeRoute
  ApiIntegrationDonationalertsCallbackRoute: typeof ApiIntegrationDonationalertsCallbackRoute
  ApiIntegrationStreamelementsAuthorizeRoute: typeof ApiIntegrationStreamelementsAuthorizeRoute
  ApiIntegrationStreamelementsCallbackRoute: typeof ApiIntegrationStreamelementsCallbackRoute
  ApiIntegrationStreamlabsAuthorizeRoute: typeof ApiIntegrationStreamlabsAuthorizeRoute
  ApiIntegrationStreamlabsCallbackRoute: typeof ApiIntegrationStreamlabsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/videos': {
      id: '/$slug/videos'
      path: '/$slug/videos'
      fullPath: '/$slug/videos'
      preLoaderRoute: typeof SlugVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/multistream': {
      id: '/_authenticated/multistream'
      path: '/multistream'
      fullPath: '/multistream'
      preLoaderRoute: typeof AuthenticatedMultistreamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/alerts/overlay': {
      id: '/alerts/overlay'
      path: '/alerts/overlay'
      fullPath: '/alerts/overlay'
      preLoaderRoute: typeof AlertsOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/privacy': {
      id: '/docs/privacy'
      path: '/docs/privacy'
      fullPath: '/docs/privacy'
      preLoaderRoute: typeof DocsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tos': {
      id: '/docs/tos'
      path: '/docs/tos'
      fullPath: '/docs/tos'
      preLoaderRoute: typeof DocsTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/donations/': {
      id: '/_authenticated/donations/'
      path: '/'
      fullPath: '/donations/'
      preLoaderRoute: typeof AuthenticatedDonationsIndexRouteImport
      parentRoute: typeof AuthenticatedDonationsRoute
    }
    '/api/alerts/stream': {
      id: '/api/alerts/stream'
      path: '/api/alerts/stream'
      fullPath: '/api/alerts/stream'
      preLoaderRoute: typeof ApiAlertsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/upload': {
      id: '/api/alerts/upload'
      path: '/api/alerts/upload'
      fullPath: '/api/alerts/upload'
      preLoaderRoute: typeof ApiAlertsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$': {
      id: '/api/chat/$'
      path: '/api/chat/$'
      fullPath: '/api/chat/$'
      preLoaderRoute: typeof ApiChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restream/media': {
      id: '/api/restream/media'
      path: '/api/restream/media'
      fullPath: '/api/restream/media'
      preLoaderRoute: typeof ApiRestreamMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/overlay/$token': {
      id: '/chat/overlay/$token'
      path: '/chat/overlay/$token'
      fullPath: '/chat/overlay/$token'
      preLoaderRoute: typeof ChatOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/dlq': {
      id: '/_authenticated/_admin/admin/dlq'
      path: '/dlq'
      fullPath: '/admin/dlq'
      preLoaderRoute: typeof AuthenticatedAdminAdminDlqRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/api/alerts/media/$assetId': {
      id: '/api/alerts/media/$assetId'
      path: '/api/alerts/media/$assetId'
      fullPath: '/api/alerts/media/$assetId'
      preLoaderRoute: typeof ApiAlertsMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/donationalerts/authorize': {
      id: '/api/integration/donationalerts/authorize'
      path: '/api/integration/donationalerts/authorize'
      fullPath: '/api/integration/donationalerts/authorize'
      preLoaderRoute: typeof ApiIntegrationDonationalertsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/donationalerts/callback': {
      id: '/api/integration/donationalerts/callback'
      path: '/api/integration/donationalerts/callback'
      fullPath: '/api/integration/donationalerts/callback'
      preLoaderRoute: typeof ApiIntegrationDonationalertsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/streamelements/authorize': {
      id: '/api/integration/streamelements/authorize'
      path: '/api/integration/streamelements/authorize'
      fullPath: '/api/integration/streamelements/authorize'
      preLoaderRoute: typeof ApiIntegrationStreamelementsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/streamelements/callback': {
      id: '/api/integration/streamelements/callback'
      path: '/api/integration/streamelements/callback'
      fullPath: '/api/integration/streamelements/callback'
      preLoaderRoute: typeof ApiIntegrationStreamelementsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/streamlabs/authorize': {
      id: '/api/integration/streamlabs/authorize'
      path: '/api/integration/streamlabs/authorize'
      fullPath: '/api/integration/streamlabs/authorize'
      preLoaderRoute: typeof ApiIntegrationStreamlabsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/streamlabs/callback': {
      id: '/api/integration/streamlabs/callback'
      path: '/api/integration/streamlabs/callback'
      fullPath: '/api/integration/streamlabs/callback'
      preLoaderRoute: typeof ApiIntegrationStreamlabsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminDlqRoute: typeof AuthenticatedAdminAdminDlqRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminDlqRoute: AuthenticatedAdminAdminDlqRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDonationsRouteChildren {
  AuthenticatedDonationsIndexRoute: typeof AuthenticatedDonationsIndexRoute
}

const AuthenticatedDonationsRouteChildren: AuthenticatedDonationsRouteChildren =
  {
    AuthenticatedDonationsIndexRoute: AuthenticatedDonationsIndexRoute,
  }

const AuthenticatedDonationsRouteWithChildren =
  AuthenticatedDonationsRoute._addFileChildren(
    AuthenticatedDonationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMultistreamRoute: typeof AuthenticatedMultistreamRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMultistreamRoute: AuthenticatedMultistreamRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlugVideosRoute: SlugVideosRoute,
  AlertsOverlayRoute: AlertsOverlayRoute,
  ApiHealthRoute: ApiHealthRoute,
  DocsPrivacyRoute: DocsPrivacyRoute,
  DocsTosRoute: DocsTosRoute,
  ApiAlertsStreamRoute: ApiAlertsStreamRoute,
  ApiAlertsUploadRoute: ApiAlertsUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSplatRoute: ApiChatSplatRoute,
  ApiRestreamMediaRoute: ApiRestreamMediaRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ChatOverlayTokenRoute: ChatOverlayTokenRoute,
  ApiAlertsMediaAssetIdRoute: ApiAlertsMediaAssetIdRoute,
  ApiIntegrationDonationalertsAuthorizeRoute:
    ApiIntegrationDonationalertsAuthorizeRoute,
  ApiIntegrationDonationalertsCallbackRoute:
    ApiIntegrationDonationalertsCallbackRoute,
  ApiIntegrationStreamelementsAuthorizeRoute:
    ApiIntegrationStreamelementsAuthorizeRoute,
  ApiIntegrationStreamelementsCallbackRoute:
    ApiIntegrationStreamelementsCallbackRoute,
  ApiIntegrationStreamlabsAuthorizeRoute:
    ApiIntegrationStreamlabsAuthorizeRoute,
  ApiIntegrationStreamlabsCallbackRoute: ApiIntegrationStreamlabsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
